# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseJavaVersion@0
  inputs:
    version: '11'
    addToPath: true

- script: |
    chmod +x ./gradlew
    ./gradlew build
  displayName: 'Grant execution permission and build with Gradle'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- script: ./gradlew runTelegramBotName
  displayName: 'Run Java class'